apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-07-18T00:22:51Z"
  generateName: ghost-dc9899fc7-
  labels:
    app: ghost
    pod-template-hash: dc9899fc7
  name: ghost-dc9899fc7-kl4gq
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: ghost-dc9899fc7
    uid: 963127f9-b411-49e9-922f-3e6bafcbf412
  resourceVersion: "11278970"
  uid: 33537d52-ff0c-4e3f-aa29-6b14bd0d852b
spec:
  containers:
  - image: ghost
    imagePullPolicy: Always
    name: ghost
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-r9f5s
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-worker03
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-r9f5s
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-07-18T00:22:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-07-18T00:24:16Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-07-18T00:24:16Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-07-18T00:22:51Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://3b7330e38c2730d57aab49242ec16a014b5d58b29eb3f15133d641ebbd7a36e6
    image: ghost:latest
    imageID: docker-pullable://ghost@sha256:aa236394ebe9b79145ce263b00a50112bf800d20d96dd360482be58a6aec64ad
    lastState: {}
    name: ghost
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-07-18T00:24:16Z"
  hostIP: 10.233.1.13
  phase: Running
  podIP: 10.244.3.174
  podIPs:
  - ip: 10.244.3.174
  qosClass: BestEffort
  startTime: "2021-07-18T00:22:51Z"
