apiVersion: v1
kind: Pod
metadata:
  name: shell-demo2
spec:
  containers:
  - name: nginx
    image: nginx
    # env:
    # - name: ilike
    #   valueFrom:
    #     configMapKeyRef:
    #       name: colors
    #       key: favorite
    envFrom:
    - configMapRef:
        name: colors
