apiVersion: v1
kind: Pod
metadata:
  name: nettool
  labels:
    name: myapp
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["sleep"]
    args: ["infinity"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 22
